/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/colours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent colours (most recent first) */
        get: operations["colourHistory"];
        put?: never;
        /**
         * Generate a colour
         * @description Generate a colour, persist it, and enqueue a colour.generated event.
         *
         *     When Cloudflare Access is provisioned, the write requires a valid Access
         *     identity JWT (`Cf-Access-Jwt-Assertion`, or a bearer token for native /
         *     direct callers). First-party channels forward the caller's token over
         *     their service binding. Auth is config-gated: unset in the demo, the
         *     endpoint is open. Reads and the SSE feed are unauthenticated.
         *
         *     Not marked as an unconditional `security` requirement because enforcement
         *     is conditional: config-gated (off until Access is provisioned) and
         *     transport-dependent (first-party service-binding callers are trusted
         *     without a token). The `accessJwt` / `bearerAuth` schemes below document
         *     the credential a direct caller presents; the 401 documents the failure.
         */
        post: operations["createColour"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/colours/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The most recently generated colour */
        get: operations["latestColour"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events feed of colour.generated events
         * @description Long-lived text/event-stream. Consumed by browser EventSource, the
         *     mobile app, and the agent. Excluded from request-conformance fuzzing
         *     because it never terminates.
         */
        get: operations["eventsStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ColourEvent: {
            /** @enum {string} */
            colour: "red" | "amber" | "green";
            /** Format: date-time */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    colourHistory: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent colours, most recent first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColourEvent"][];
                };
            };
            /** @description Invalid query parameter. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createColour: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The generated colour. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColourEvent"];
                };
            };
            /** @description Missing or invalid Access token (only when Access is provisioned). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited — too many colour generations. Retry after the Retry-After interval. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    latestColour: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The latest colour. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColourEvent"];
                };
            };
            /** @description No colours generated yet. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    eventsStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An SSE stream of colour payloads. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
