/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The calling user's todos (most recent first) */
        get: operations["listTodos"];
        put?: never;
        /**
         * Create a todo
         * @description Create a todo for the calling user, persist it, and enqueue a
         *     todo.created event.
         *
         *     When Cloudflare Access is provisioned, every call requires a valid
         *     Access identity JWT (`Cf-Access-Jwt-Assertion`, or a bearer token for
         *     native / direct callers). First-party channels forward the caller's
         *     token over their service binding. The `accessJwt` / `bearerAuth`
         *     schemes below document the credential; the 401 documents the failure.
         */
        post: operations["createTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** A single todo by id */
        get: operations["getTodo"];
        put?: never;
        post?: never;
        /** Delete a todo */
        delete: operations["deleteTodo"];
        options?: never;
        head?: never;
        /**
         * Rename and/or set completion on a todo
         * @description Partial update. Completing emits todo.completed; renaming or
         *     un-completing emits todo.updated. `completed_at` is set when a todo
         *     transitions to completed and cleared when it is un-completed.
         */
        patch: operations["updateTodo"];
        trace?: never;
    };
    "/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events feed of the calling user's todo events
         * @description Long-lived text/event-stream, scoped to the calling user — each frame
         *     is `{type, data}` where `type` is one of the todo event types and
         *     `data` is the todo snapshot. Consumed by the web proxy, the mobile
         *     app's SSE reader, and the agent. Excluded from request-conformance
         *     fuzzing because it never terminates.
         */
        get: operations["eventsStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Todo: {
            /** Format: uuid */
            id: string;
            title: string;
            completed: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at: string | null;
        };
        NewTodo: {
            title: string;
        };
        /** @description At least one of title / completed must be present. */
        TodoPatch: {
            title?: string;
            completed?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTodos: {
        parameters: {
            query?: {
                /** @description Filter by completion state. */
                completed?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user's todos, most recent first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"][];
                };
            };
            /** @description Missing or invalid Access token (only when Access is provisioned). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid query parameter. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createTodo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewTodo"];
            };
        };
        responses: {
            /** @description The created todo. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            /** @description Missing or invalid Access token (only when Access is provisioned). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid body — title missing, empty, or over 256 characters. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited — too many writes. Retry after the Retry-After interval. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The todo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            /** @description Missing or invalid Access token (only when Access is provisioned). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such todo for the calling user (missing ids and other users' ids are indistinguishable). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (emits todo.deleted). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid Access token (only when Access is provisioned). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such todo for the calling user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited — too many writes. Retry after the Retry-After interval. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodoPatch"];
            };
        };
        responses: {
            /** @description The updated todo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            /** @description Missing or invalid Access token (only when Access is provisioned). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such todo for the calling user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid body — empty patch, invalid title, or invalid completed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited — too many writes. Retry after the Retry-After interval. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    eventsStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An SSE stream of the user's todo events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Missing or invalid Access token (only when Access is provisioned). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
